import Foundation

/// Heuristic classifier for transactional mail — receipts, order confirmations, invoices, bills,
/// and shipping notifications. Uses subject-line patterns only, no body content. The aim is
/// **high precision, modest recall**: better to miss some receipts than to mis-flag a personal
/// email about an order so the user can't auto-clean it.
public enum TransactionalDetector {
    /// Subject substrings that very reliably indicate transactional mail. Lowercase-compared.
    /// Curated to avoid common false positives ("your weekly order of news" — would match "your
    /// order" but is excluded by the newsletter guard below).
    private static let subjectKeywords: [String] = [
        "account statement",
        "appointment confirmation",
        "auto-pay",
        "auto pay",
        "auto payment",
        "auto-renewal",
        "autopay",
        "bank transfer",
        "bill available",
        "bill is due",
        "bill is ready",
        "billing statement",
        "booking confirmation",
        "card charged",
        "card ending",
        "charged your card",
        "checkout receipt",
        "confirmed your order",
        "delivery confirmation",
        "delivery estimate",
        "delivery update",
        "deposit received",
        "digital receipt",
        "e-receipt",
        "electronic receipt",
        "estimate approved",
        "invoice",
        "invoice #",
        "invoice available",
        "invoice due",
        "invoice from",
        "invoice paid",
        "invoice payment",
        "invoice ready",
        "itinerary",
        "monthly statement",
        "order #",
        "order accepted",
        "order confirmed",
        "order confirmation",
        "order details",
        "order has shipped",
        "order is confirmed",
        "order is on",
        "order is ready",
        "order placed",
        "order received",
        "order shipped",
        "order status",
        "order update",
        "out for delivery",
        "paid invoice",
        "payment accepted",
        "payment confirmation",
        "payment declined",
        "payment due",
        "payment failed",
        "payment posted",
        "payment processed",
        "payment receipt",
        "payment received",
        "payment reminder",
        "payment scheduled",
        "payment successful",
        "payment unsuccessful",
        "purchase confirmation",
        "purchase receipt",
        "purchase successful",
        "ready for pickup",
        "receipt",
        "receipt for",
        "recurring payment",
        "refund approved",
        "refund confirmation",
        "refund issued",
        "refund processed",
        "renewal confirmation",
        "reservation confirmation",
        "return approved",
        "return confirmation",
        "return received",
        "return request",
        "scheduled payment",
        "service appointment",
        "service confirmation",
        "shipment confirmation",
        "shipment notification",
        "shipping confirmation",
        "shipping update",
        "shipped your",
        "shipped:",
        "statement available",
        "statement is ready",
        "subscription confirmation",
        "subscription invoice",
        "subscription renewal",
        "ticket confirmation",
        "tickets confirmed",
        "tracking #",
        "tracking information",
        "tracking number",
        "transaction",
        "transaction confirmation",
        "transaction receipt",
        "transfer confirmation",
        "upcoming payment",
        "your appointment",
        "your bill",
        "your booking",
        "your invoice",
        "your itinerary",
        "your order",
        "your payment",
        "your purchase",
        "your receipt",
        "your refund",
        "your reservation",
        "your shipment",
        "your statement",
        "your tickets",
        "your tracking"
    ]

    /// Lowered-case keyword list. Computed once so `matches` doesn't recompute the lowercased
    /// keyword vector for every header.
    private static let loweredKeywords: [String] = subjectKeywords.map { $0.lowercased() }

    /// Pure-input variant used at `MessageHeader` init time, before the value-typed header is
    /// fully formed. Caller passes the already-derived newsletter flag.
    public static func matches(subject: String, isLikelyNewsletter: Bool) -> Bool {
        if isLikelyNewsletter { return false }
        let lowered = subject.lowercased()
        return loweredKeywords.contains { lowered.contains($0) }
    }
}
